eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka

spring:
  security:
    user:
      name: laohan
      password: 123
  application:
    name: ylt-diagnose

server:
  port: 8086
