spring:
  application:
    name: turbine
eureka:
  client:
    service-url:
      defaultZone: http://laohan:123@localhost:8761/eureka
turbine:
  combine-host-port: true
  appConfig: outpatient,test
  clusterNameExpression: new String('default')
#  aggregator:
#    cluster-config: servers
#  InstanceMonitor:
#    eventStream:
#      skipLineLogic:
#        enabled: false
#turbine.InstanceMonitor.eventStream.skipLineLogic.enabled = false

server:
  port: 8766
